name: Sync README

on:
  push:
    paths:
      - README.md

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install googletrans==4.0.2 beautifulsoup4

      # Executar o script
      - name: Run sync script
        run: python sync_readme.py

      # Commit das mudanças
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add translations/README_pt.md translations/README_es.md translations/README_zh-cn.md # Adiciona todos os arquivos modificados no diretório
          git commit -m "Atualização automática dos arquivos" || echo "Nada para commitar"
          git diff --quiet || git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Luis01Felipe/Luis01Felipe.git" HEAD:main
